$schema: https://azuremlschemas.azureedge.net/latest/commandComponent.schema.json
name: train_component
version: 1
code: ../
entry: train.py

inputs:
  train_data:
    type: uri_file
    description: Preprocessed training CSV

outputs:
  model:
    type: uri_folder
    description: Trained model artifacts
  metrics:
    type: uri_file
    description: Model evaluation metrics

environment: azureml:AzureML-sklearn-1.0-ubuntu20.04-py38-cpu@latest

command: >-
  bash -lc "python -m pip install --no-cache-dir -r components/requirements.txt && python train.py --train ${{inputs.train_data}} --model_output ${{outputs.model}} --metrics_output ${{outputs.metrics}}"
